[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
nft_mint_vault = "CXGL4hPhcChVXwZX3cz6F8E6wfjqbEWWTkKzAdoc9ZFn"

[programs.devnet]
nft_mint_vault = "CXGL4hPhcChVXwZX3cz6F8E6wfjqbEWWTkKzAdoc9ZFn"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "devnet"
wallet = "~/my-keypair.json"

[test]
startup_wait = 20000

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
